version: "3.9"

services:
  backend:
    image: ${ACR_LOGIN_SERVER}/expense_backend:latest
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: sqlite:////home/data/expenses.db
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    restart: always

  frontend:
    image: ${ACR_LOGIN_SERVER}/expense_frontend:latest
    ports:
      - "80:80"
    environment:
      VITE_API_URL: http://localhost:8000
    restart: always